export const Robots = [
  { id: 1, name: "John Doe", username: "johnd", email: "john@example.com" },
  { id: 2, name: "Jane Smith", username: "janes", email: "jane@example.com" },
  { id: 3, name: "Alice Johnson", username: "alicej", email: "alice@example.com" },
  { id: 4, name: "Bob Brown", username: "bobb", email: "bob@example.com" },
  { id: 5, name: "Charlie Davis", username: "charlied", email: "charlie@example.com" },
  { id: 6, name: "Diana Miller", username: "dianam", email: "diana@example.com" },
  { id: 7, name: "Ethan Wilson", username: "ethanw", email: "ethan@example.com" },
  { id: 8, name: "Fiona Clark", username: "fionac", email: "fiona@example.com" },
  { id: 9, name: "George Lewis", username: "georgel", email: "george@example.com" },
  { id: 10, name: "Hannah Young", username: "hannahy", email: "hannah@example.com" },
  { id: 11, name: "Ian King", username: "iank", email: "ian@example.com" },
  { id: 12, name: "Julia Wright", username: "juliaw", email: "julia@example.com" },
  { id: 13, name: "Kevin Scott", username: "kevins", email: "kevin@example.com" },
  { id: 14, name: "Laura Hall", username: "laurah", email: "laura@example.com" },
  { id: 15, name: "Mike Adams", username: "mikea", email: "mike@example.com" },
  { id: 16, name: "Nathan Brooks", email: "nathan@example.com" },
  { id: 17, name: "Olivia Bennett", email: "olivia@example.com" },
  { id: 18, name: "Liam Turner", email: "liam@example.com" },
  { id: 19, name: "Ava Parker", email: "ava@example.com" },
  { id: 20, name: "Mason Cooper", email: "mason@example.com" },
  { id: 21, name: "Sophia Murphy", email: "sophia@example.com" },
  { id: 22, name: "Logan Reed", email: "logan@example.com" },
  { id: 23, name: "Isabella Gray", email: "isabella@example.com" },
  { id: 24, name: "Elijah Hughes", email: "elijah@example.com" },
  { id: 25, name: "Mia Foster", email: "mia@example.com" },
  { id: 26, name: "James Simmons", email: "james@example.com" },
  { id: 27, name: "Amelia Ward", email: "amelia@example.com" },
  { id: 28, name: "Benjamin Ross", email: "benjamin@example.com" },
  { id: 29, name: "Charlotte Rivera", email: "charlotte@example.com" },
  { id: 30, name: "Lucas Cox", email: "lucas@example.com" },
  { id: 31, name: "Harper Peterson", email: "harper@example.com" },
  { id: 32, name: "Henry Jenkins", email: "henry@example.com" },
  { id: 33, name: "Evelyn Kelly", email: "evelyn@example.com" },
  { id: 34, name: "Alexander Barnes", email: "alexander@example.com" },
  { id: 35, name: "Abigail Powell", email: "abigail@example.com" }
];
